import '@style/main.css';
import classNames from 'classnames';
import { Inter } from 'next/font/google';

import Footer from '@module/Footer';
import Navbar from '@module/Navbar';

import type { Metadata } from 'next';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'WolPortal',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={classNames(inter.className, 'bg-wolblack')}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
